In [ ]:
from google.colab import files
files.upload()
print("training file uploaded")

Saving training.json to training.json
training file uploaded


In [ ]:
import json
import codecs
import pandas as pd
from sklearn.preprocessing import LabelEncoder

#dataframe from the json file
data = pd.DataFrame(json.load(codecs.open('training.json', 'r', 'utf-8-sig')))
print(data.head(10))
print(data.isnull().sum())
print(data.columns.values)
print(data.info())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           4.6          3.4           1.4          0.3  setosa
6           5.0          3.4           1.5          0.2  setosa
7           4.4          2.9           1.4          0.2  setosa
8           4.9          3.1           1.5          0.1  setosa
9           5.4          3.7           1.5          0.2  setosa
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64
['sepal_length' 'sepal_width' 'petal_length' 'petal_width' 'species']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 5 columns):
 #   Column        

In [ ]:

lab_enc = LabelEncoder()
data["species"] = lab_enc.fit_transform(data["species"])
print(data.head(10))
print(data['species'].unique)

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0
5           4.6          3.4           1.4          0.3        0
6           5.0          3.4           1.5          0.2        0
7           4.4          2.9           1.4          0.2        0
8           4.9          3.1           1.5          0.1        0
9           5.4          3.7           1.5          0.2        0
<bound method Series.unique of 0      0
1      0
2      0
3      0
4      0
      ..
142    2
143    2
144    2
145    2
146    2
Name: species, Length: 147, dtype: int64>


In [ ]:
train_x = data.iloc[:, :-1]
print(train_x.head())

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


In [ ]:

train_y = data['species']
print(type(train_y))
print(train_y)

#train_y = pd.get_dummies(train_y.species, prefix='species')
#print(train_y)


<class 'pandas.core.series.Series'>
0      0
1      0
2      0
3      0
4      0
      ..
142    2
143    2
144    2
145    2
146    2
Name: species, Length: 147, dtype: int64


In [ ]:

import numpy as np
import matplotlib.pyplot as pl
%matplotlib inline

x = np.linspace(-10,10,100);
# function to compute the sigmoid
sigmoid = lambda x: 1/(1 + np.exp(-x));

# initialize the weights between input layer and hidden layer
W1 = 2*np.random.rand(5, 4) - 2;

# initialize the weights between hidden layer and output layer
W2 = 2*np.random.rand(3, 5) - 1;

print(W1)
print("")
print(W2)

[[-0.78979717 -1.00073549 -1.7680751  -1.56977228]
 [-1.25672023 -1.79179026 -1.51135124 -0.98738653]
 [-1.33174566 -1.67825599 -1.80049354 -0.43995251]
 [-0.56165851 -0.29061283 -0.65175763 -0.54650134]
 [-1.18386625 -1.45734999 -0.63110659 -1.96342342]]

[[-0.95381732  0.60118892  0.3581501  -0.99006527 -0.19105522]
 [ 0.00234468  0.29439922 -0.60709096 -0.27640321  0.70986787]
 [-0.52999124 -0.94179478 -0.48528955  0.76872926  0.26691665]]


In [ ]:
################################################################################
# This function implements the backpropagation algorithm for a simple 4-5-1 ANN
#  W1 and W2 are the weight matrices of the respective layers:
#   W1 is the weight matrix between the input layer and hidden layer
#   W2 is the weight matrix between the hidden layer and output layer.
#  X and D are the input and correct output of the training data (XOR), respectively.
################################################################################

def forwardprop(W1, W2, x, d):

      ##########################
        # forward propagation step
        ##########################
        # calculate the weighted sum of hidden node
        v1 = np.dot(W1,x);

        #pass the weighted sum to the activation function, this gives the outputs from hidden layer
        y1 = sigmoid(v1);

        #calculate the weighted sum of the output layer
        v = np.dot(W2,y1);

        # pass it to the activation function, this returns the output of the third layer
        y = sigmoid(v);

        if(d == None): return y;

        #calculate the error, difference between correct output and computed output
        e = d - y;

        #calculate delta, derivative of the activation function times the error
        # note that 𝜎′(𝑥)=𝜎(𝑥)∙(1− 𝜎(𝑥)) = y * (1-y)
        delta = y*(1-y)*e; # element wise multiplication

        return delta, y1 , y;


def backprop(W1, W2, X, D):
    alpha = 0.9; # learning rate
    N=147;

    for k in range(0,N):
        x = X[k, :].T; #inputs from training data

        d = D[k]; # correct output from training data

        #delta, y1, y = forwardprop(W1, W2, x, d);

        ##########################
        # forward propagation step
        ##########################
        # calculate the weighted sum of hidden node
        v1 = np.dot(W1,x);

        #pass the weighted sum to the activation function, this gives the outputs from hidden layer
        y1 = sigmoid(v1);

        #calculate the weighted sum of the output layer
        v = np.dot(W2,y1);

        # pass it to the activation function, this returns the output of the third layer
        y = sigmoid(v);

        if(d == None): return y;

        #calculate the error, difference between correct output and computed output
        e = d - y;

        #calculate delta, derivative of the activation function times the error
        # note that 𝜎′(𝑥)=𝜎(𝑥)∙(1− 𝜎(𝑥)) = y * (1-y)
        delta = y*(1-y)*e; # element wise multiplication

        ###########################
        # Backward propagation step
        ###########################
        # propagate the output node delta, δ, backward, and calculate the deltas of the hidden layer.
        e1 = np.dot(W2.T, delta);

        delta1 = y1*(1-y1)*e1;  # element wise multiplication

        # Adjust the weights according to the learning rule
        delta1.shape=(5,1) # column vector of deltas for the hidden layer
        x.shape=(1,4) # row vector of the current input
        dW1 = alpha*np.dot(delta1,x);
        W1 = W1 + dW1;


        y1.shape = (1,5)
        delta.shape=(3,1)
        dW2 = alpha*np.dot(delta,y1);
        W2 = W2 + dW2;
    return W1, W2;



In [ ]:
# run the backprop algorithm to compute the weights
for epoch in range(1,10000): # train
    W1, W2 = backprop(W1, W2,train_x.to_numpy(), train_y);

In [ ]:
train_x.shape

(147, 4)

In [ ]:

N = 147
X = train_x.to_numpy()

for k in range(0,N):
    x = X[k, :].T; #inputs from training data

    y = forwardprop(W1, W2, x, None);
    print(y)


[0.0008418  0.00084178 0.0008418 ]
[0.0009187  0.00091871 0.00091871]
[0.00085389 0.00085391 0.00085391]
[0.00098349 0.00098351 0.00098351]
[0.00083874 0.00083873 0.00083874]
[0.0008647  0.00086469 0.0008647 ]
[0.00086655 0.00086653 0.00086655]
[0.00101906 0.00101914 0.0010191 ]
[0.00091504 0.00091505 0.00091505]
[0.00083907 0.00083904 0.00083906]
[0.00091491 0.00091489 0.00091491]
[0.00089607 0.0008961  0.00089609]
[0.00084169 0.00084183 0.00084176]
[0.00083039 0.00083035 0.00083038]
[0.00083121 0.00083117 0.0008312 ]
[0.0008323  0.00083227 0.0008323 ]
[0.00084683 0.00084681 0.00084683]
[0.00085855 0.00085851 0.00085854]
[0.00084099 0.00084096 0.00084099]
[0.00094206 0.00094202 0.00094205]
[0.00085273 0.0008527  0.00085272]
[0.00083079 0.00083082 0.00083081]
[0.00152818 0.00152814 0.00152817]
[0.00166301 0.00166298 0.00166301]
[0.0011883  0.0011883  0.00118831]
[0.00098435 0.00098432 0.00098434]
[0.00085185 0.00085183 0.00085185]
[0.00084593 0.00084592 0.00084593]
[0.00102941 0.001029

In [ ]:
# upload test.json
files.upload()

Saving test.json to test.json


{'test.json': b'[\r\n  {\r\n    "sepal_length": 5.4,\r\n    "sepal_width": 3.9,\r\n    "petal_length": 1.7,\r\n    "petal_width": 0.4,\r\n    "species": "setosa"\r\n  },\r\n  {\r\n    "sepal_length": 5.9,\r\n    "sepal_width": 3,\r\n    "petal_length": 5.1,\r\n    "petal_width": 1.8,\r\n    "species": "virginica"\r\n  },\r\n  \r\n  {\r\n    "sepal_length": 5.7,\r\n    "sepal_width": 2.9,\r\n    "petal_length": 4.2,\r\n    "petal_width": 1.3,\r\n    "species": "versicolor"\r\n  }\r\n]'}

In [ ]:
test_data = pd.DataFrame(json.load(codecs.open('test.json', 'r', 'utf-8-sig')))
print(test_data.head())
print(test_data.info())

   sepal_length  sepal_width  petal_length  petal_width     species
0           5.4          3.9           1.7          0.4      setosa
1           5.9          3.0           5.1          1.8   virginica
2           5.7          2.9           4.2          1.3  versicolor
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  3 non-null      float64
 1   sepal_width   3 non-null      float64
 2   petal_length  3 non-null      float64
 3   petal_width   3 non-null      float64
 4   species       3 non-null      object 
dtypes: float64(4), object(1)
memory usage: 248.0+ bytes
None


In [ ]:
class_names = ['setosa','versicolor','virginica']

In [ ]:
x_test = test_data.drop(['species'], axis=1)
y_test = test_data['species']

In [ ]:
x_test = x_test.to_numpy()

for k in range(3):
    x = x_test[k, :].T; #inputs from training data
    ##########################
    # forward propagation step
    ##########################
    # calculate the weighted sum of hidden node
    v1 = np.dot(W1,x);
    #pass the weighted sum to the activation function, this gives the outputs from hidden layer
    y1 = sigmoid(v1);
    #calculate the weighted sum of the output layer
    v = np.dot(W2,y1);
    # pass it to the activation function, this returns the output of the third layer
    y = sigmoid(v);
    print("Actual value: ", y_test[k], "\n Predicted class: ",  class_names[y.argmax()])
    #print(f"Actual value {y_test.iloc[k]}\n")

Actual value:  setosa 
 Predicted class:  setosa
Actual value:  virginica 
 Predicted class:  versicolor
Actual value:  versicolor 
 Predicted class:  versicolor
